//https://gltf-viewer.donmccurdy.com/
/* 
https://animejs.com/
https://greensock.com/
https://lottiefiles.com/
https://babeljs.io/

redstapler
*/

let circleGem = Object;
let triangleGem = Object;
let squareGem = Object;


let gemArray = [];



function gemPush(gem){
    
    //pushes the gems from QR scan into the gem Array
    if (gemArray === 3){
        //stop them from pushing into the array
    } else {
        gemArray.push(gem)
    }

}

function swordQR(){
    
}

